title: 			HiFightTH
description: 	Fighting Games Highlight
author: 		HiFightTH
logo: 			/static/img/hifight_avatar.jpg
github: 
about: 			Fighting Games Highlight

#baseurl: "https://hifight.github.io"
url: 		"https://hifight.github.io"
#url: 		"http://localhost:4000"

allowsearch: true

disqus_shortname: 
google_analytics: UA-62718038-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
